import requests
import json

OGN_DDB_URL = "https://ddb.glidernet.org/download/?j=1&t=1"

# aircrafts which we do not want to track
no_mapping = [
    "Castel 25-S",
    "MD 600",
    "Valmet PIK-23 Towmaster",
    "LET LF-107 Lunak",
    "Swift 3-E",
    "Breguet 904",
    "MikroKopter Quadro",
    "DJI S800",
    "DJI S1000",
    "Parrot senseFly",
    "Wild Thing WT01",
    "Scottish Aviation Bulldog",
    "A22 Foxbat",
    " FK 9 Mark VI",
    "Piccolo B",
    "Smyk",
    "Std. Austria SH1",
    "Bristell B23",
    "DJI Agras",
    "Archaeopteryx-E",
    "Thruster",
    "ICP Savannah",
    "Douglas Dakota",
    "TB-30 Epsilon",
    "Avro Lancaster",
    "AS 365",
    "PA34 Seneca",
    "DJI Mavic",
    "LET LF-109 Pionyr",
    "Bell 429",
    "RF 47",
    "Viper SD-4",
    "AFH-22",
    "AK-8",
    "Parrot AR.Drone",
    "Slingsby T-21B",
    "SZD-45 Ogar",
    "Aeromot AMT-200S Super Ximango",
    "DJI Matrice",
    "Archaeopteryx",
    "Piper PA-44",
    "Piper PA-38 Tomahawk",
    "Slingsby T.43 Skylark 3C",
    "Schreder HP-18",
    "Zuni II",
    "Apollo Fox",
    "C 38",
    "Vans RV-6",
    "DJI Mini",
    "Parachute",
    "Glasair III",
    "Cessna 404",
    "PZL W-3 Sokol",
    "Bristell NG5",
    "SGS 2-32",
    "Slingsby T34 Sky",
    "MS-887 Rallye 125",
    "Mu 28",
    "HP-24",
    "Helisports CH77",
    "SZD-22 Mucha Standard",
    "Piper PA-17",
    "LP-15 Nugget",
    "Glastar",
    "Drone/UAV",
    "Unknown",
    "Paraglider",
    "A 109",
    "A 119",
    "A2 CZ Ellipse Spirit",
    "A380",
    "A60 Fauconnet",
    "AK-2R",
    "AS 350",
    "AS202/32TP Turbo Bravo",
    "AV 36 Fauvel",
    "AVo 68 Samburo",
    "Aero Boero 180",
    "Allegro 2000",
    "Alliance 34",
    "Alpaero Choucas",
    "Alto 912 TG ",
    "Antonov 2",
    "Aquila A210",
    "ArrowCopter",
    "Zlin 50",
    "Phoenix",
    "FK9 Mark 2",
    "Mustang (UL)",
    "Pilatus PC-7",
    "Cessna 150",
    "L 13 SEH Vivat",
    "SZD-23 Bocian 2",
    "MD 500",
    "Robinson R44",
    "C30S Edelweiss",
    "DV20 Katana",
    "Cessna 120",
    "Ultralight",
    "PIK-15 Hinu",
    "Jodel D113",
    "Avro Vulcan",
    "Rutan VariEze",
    "Experimental",
    "Pilatus P3",
    "Maule M-7",
    "RF 5 b",
    "AutoGyro MTOsport",
    "Bellanca Scout",
    "Bell 407",
    "Polikarpov Po-2",
    "BX2 Cherry",
    "Jodel D112",
    "Yak-12",
    "Vulcanair P68C",
    "Motorglider",
    "Vans RV-9",
    "Cessna 175",
    "Extra 330",
    "Rallye 180T-D",
    "VL3 Evolution",
    "CallAir A-9",
    "MikroKopter Okto",
    "Z-226 trener",
    "Zlin 142",
    "Tetra-15",
    "Sport Vega",
    "Topaze",
    "Slingsby Type 42",
    "Samba XXL",
    "HU 269",
    "Cabri G2",
    "Socata Rallye 235CA-M",
    "DJI Inspire",
    "Piper PA-22 Tripacer",
    "K1200",
    "Tecnam P2006T",
    "MS-894 Minerva",
    "Pipistrel Virus",
    "WA22 Super-Javelot",
    "FM250 Vampire",
    "Hawker Hurricane",
    "SGS 1-35",
    "Vans RV-4",
    "WA26 Squale",
    "L-60 Brigadyr",
    "Parrot Bebop",
    "Pilatus PC-12",
    "M-200 Foehn",
    "Pioneer 300",
    "Zlin 526F",
    "RF 3",
    "Jodel D18",
    "PA-25 Pawnee",
    "Marianne",
    "SFS-31 Milan",
    "DA40",
    "Europa XS",
    "Ground Station",
    "Ikarus C42 B",
    "Grumman AA-5",
    "Sinus",
    "Stratos 300",
    "Banhidi Gerle",
    "Grob G120TP",
    "MikroKopter Hexa",
    "DynAero MCR-4S",
    "Cessna 185",
    "Cirrus SR20",
    "DR-400",
    "Robinson R22",
    "LG-425 Sohaj",
    "Vans RV-12",
    "Skylane Airlony",
    "HU 369",
    "Luscombe 8E",
    "JP 15/34",
    "Jodel D120",
    "Gyrocopter",
    "EC 120",
    "TL-2000 Sting",
    "GP 15 SE Jeta",
    "Cirrus SR22",
    "Capstan",
    "Jodel DR-1050",
    "MS-892 Commodore",
    "Crystal",
    "DHC-1 Chipmunk",
    "Motorplane",
    "Sensation",
    "DR-300",
    "Luscombe 8F",
    "Bellanca Citabria",
    "Valentin Taifun",
    "Mooney",
    "Fuji FA-200",
    "EC 135",
    "Roland Z602 XL",
    "Rockwell Commander 114a",
    "ENF 480",
    "Eurostar EV97",
    "Rubik R-26 Gobe",
    "P 220 Koala",
    "Cessna 177",
    "Cessna 305",
    "Ikarus C42 C",
    "Ultralight Glider",
    "Jodel D119",
    "EuroFox",
    "DR-250",
    "Supermarine Spitfire",
    "DA20 Katana",
    "Cessna 206",
    "JP 15/36",
    "Cessna 182",
    "SGS 1-26",
    "Cessna T303",
    "GP 14 SE Velo",
    "Other",
    "DynAero MCR-01",
    "Maule M-7-235",
    "DynAero MCR-M",
    "Different Aircraft",
    "PA-30 Twin Comanche",
    "Midour",
    "Silent-IN",
    "Robinson R66",
    "Pegasus",
    "PZL-104 Wilga",
    "SkyRanger Nynja",
    "OldTimer",
    "Breguet 901",
    "Vans RV-6a",
    "Lisunov Li-2",
    "Pegase Trainer",
    "Beech Bonanza V35",
    "Diamond DA42",
    "FK14",
    "TB-9 Tampico",
    "Towplane",
    "Vans RV-8",
    "RF 10",
    "Tecnam  P2002 JF",
    "IS-28M2",
    "TB-10 Tobago",
    "EC 130",
    "Scheibe SF 40",
    "PIK-30",
    "WA30 Bijave",
    "TB-20 Trinidad",
    "PA-18 Super Cub",
    "Cessna 152",
    "Flight Design CTSW",
    "PA-28",
    "Cessna 172",
    "RF 7",
    "Pilatus PC-6",
    "Piaggio P.149",
    "LET L-33 Solo",
    "Bell 206",
    "DJI Phantom",
    "Balloon",
    "Maule MX7-180A",
    "SportCruiser",
    "SkyArrow",
    "Jodel D140",
    "WA28 Espadon",
    "Cessna 208",
    "BK 117",
    "Husky A-1",
    "Rubik R-18 Kanya",
    "TST-10",
    "IS-29D2",
    "Bolkow 208",
    "SkyRanger",
    "Helicopter",
    "WA21 Javelot",
    "Olympia 463",
    "HangGlider",
    "MS-893 Commodore",
    "Piper J-3 Cub",
    "UFO",
    "Zlin 242",
    "JOB 15",
    "Remos GX",
    "Zodiac CH601XL",
    "WT9 Dynamic",
]

mapping_file = open("ogn_ddb_mapping.json")
mapping = json.load(mapping_file)
all_we_know = list([k for (k, v) in mapping.items() if v]) + no_mapping


def test_all_mapped():
    """Test if all aircraft names in the ogn ddb are either mapped to a WeGlide type or ignored"""
    response = requests.get(OGN_DDB_URL)
    devices = response.json()["devices"]
    for device in devices:
        name = device["aircraft_model"]
        if not name:
            continue

        assert name in all_we_know
